name: Quality Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  analyze-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Configura Java 11, requerido por tu build.gradle
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      # Configura una versi칩n de Flutter compatible
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2' 
          channel: 'stable'
          cache: true

      # Instala TODAS las dependencias de tu proyecto real
      - name: Install dependencies
        working-directory: ./asistenciacontrol
        run: flutter pub get

      # Analiza el c칩digo completo (ahora funcionar치 porque las dependencias est치n instaladas)
      - name: Analyze code
        working-directory: ./asistenciacontrol
        run: flutter analyze

      # Ejecuta tus pruebas unitarias
      - name: Run tests
        working-directory: ./asistenciacontrol 
        run: flutter test