name: asistenciacontrol
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  data_table_2: ^2.4.2
  fl_chart: ^0.65.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  geolocator: ^13.0.2
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  lottie: ^3.2.0
  flutter_localizations:
    sdk: flutter
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  image_network: ^2.6.0
  firebase_storage: ^12.4.4
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geocoding: ^3.0.0
  firebase_database: ^11.3.4
  flutter_svg: ^2.0.17
  local_auth: ^2.3.0
  google_maps_flutter: ^2.10.1
  cryptography: ^2.7.0
  flutter_staggered_animations: ^1.1.0
  lucide_icons: ^0.257.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/location_pin.png
