name: asistenciacontrol
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  # Solo se necesita flutter sdk para la estructura básica del proyecto
  flutter:
    sdk: flutter

dev_dependencies:
  # La única dependencia real para tu archivo de test
  flutter_test:
    sdk: flutter
  
  # flutter_lints es necesario para que `flutter analyze` no dé un error por su ausencia,
  # aunque no lo vayamos a usar de forma efectiva sin las otras dependencias.
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true